
servicio:
    port: 4567
    ambiente: "Desarrollo"
    
base:
  adapter: "mysql2"
  host: "192.168.0.101"
  port: "3306"
  username: "hacetodo"
  password: "hacetodo"
  dbname: 'peliculas_desa'
  
params:
    pelisXdirec: 2
    pelisXactor: 2
    
